trigger:
  branches:
    include:
    - dev
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: vs2017-win2016
    steps:
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: cp .\local.sample.settings.json .\local.settings.json
        workingDirectory: $(System.DefaultWorkingDirectory)/CommunicationApi
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: >
          $(System.DefaultWorkingDirectory)/CommunicationApi/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release
    - task: ArchiveFiles@2
      displayName: Archive files
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/publish_output
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@1
      inputs:
        path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifactName: drop
- stage: Test
  displayName: Test stage
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: vs2017-win2016
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*UnitTest/*.csproj'
        arguments: --configuration Debug
- stage: Deploy
  displayName: Deploy stage
  dependsOn:
  - Build
  - Test
  condition: succeeded('Build')
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment:
      name: development
    pool:
      vmImage: vs2017-win2016
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: Azure functions app deploy
            inputs:
              azureSubscription: 9e9e1a84-e844-4b3c-a731-23d189b43a2e
              appType: functionApp
              appName: fa-communication-api-dev
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip

